keys:
  # Users
  - users:
      - &zebradil age188h98rs643kglmetvqt3hhnllw0ga45jg94p8xar2qe0c987k59q9qxv3v
  # Hosts
  - hosts:
      - &tuxedo age1nqcqaf0e2jzj7w9pj3d3cdlf8havcmzdfth8gzvgm0drwlqrnveq8eu8j2
  # CI (GitHub Actions); private key stored as the SOPS_AGE_KEY repo secret
  - ci:
      - &github-ci age1avy74tmpl5tws934r0rs9rxgcul2k3d942xmn4heh4t0xuf584msr7cewl

creation_rules:
  - path_regex: secrets/users/zebradil\.ya?ml$
    key_groups:
      - age:
          - *tuxedo
          - *zebradil
  - path_regex: secrets/hosts/common\.ya?ml$
    key_groups:
      - age:
          - *tuxedo
          - *zebradil
  - path_regex: secrets/hosts/tuxedo/ssh_host_ed25519\.key$
    key_groups:
      - age:
          - *tuxedo
          - *zebradil
  - path_regex: secrets/cache\.ya?ml$
    key_groups:
      - age:
          - *zebradil
          - *github-ci
  - path_regex: secrets/.*\.ya?ml$
    key_groups:
      - age:
          - *zebradil
