name: Test Flake

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/nix-ci.yaml
    with:
      nix-infra-ref: ${{ github.sha }}
      discovery-types: |
        checks
      runner-mapping: |
        x86_64-linux:ubuntu-latest
        aarch64-darwin:macos-15
      cache-pull-url: https://znix.zebradil.dev
      cache-public-key: znix.zebradil.dev:nvr0OQFRddbHGopQbyLbLXQnntFBDKp23tqQq+msppw=
      push-to-cache: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    secrets:
      cache-signing-key: ${{ secrets.CACHE_PRIVATE_KEY }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      cache-s3-url: ${{ secrets.CACHE_URL != '' && format('s3://{0}', secrets.CACHE_URL) || '' }}

  required-checks:
    name: required-checks
    needs: [ci]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Verify CI result
        env:
          CI_RESULT: ${{ needs.ci.result }}
        run: |
          echo "ci result: $CI_RESULT"
          if [[ "$CI_RESULT" != "success" ]]; then
            exit 1
          fi
