name: Build and Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run-flake-update:
        description: Run nix flake update before building
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    uses: ./.github/workflows/nix-update.yaml
    with:
      discovery-types: |
        checks
      attr-filter: '-build$|^checks\.x86_64-linux\.'
      runner-mapping: |
        x86_64-linux:ubuntu-latest
        aarch64-linux:ubuntu-24.04-arm
        aarch64-darwin:macos-26
      cache-pull-url: https://znix.zebradil.dev
      cache-public-key: znix.zebradil.dev:nvr0OQFRddbHGopQbyLbLXQnntFBDKp23tqQq+msppw=
      run-flake-update: ${{ github.event_name == 'workflow_dispatch' && inputs.run-flake-update }}
      auto-commit: ${{ github.event_name == 'workflow_dispatch' && inputs.run-flake-update }}
      kasha-flake: znix
    secrets:
      sops-age-key: ${{ secrets.SOPS_AGE_KEY }}
      ci-push-ssh-key: ${{ secrets.CI_PUSH_DEPLOY_KEY }}
