name: Build and Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run-flake-update:
        description: Run nix flake update before building
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  publish:
    uses: ./.github/workflows/nix-update.yaml
    with:
      discovery-types: |
        checks
      runner-mapping: |
        x86_64-linux:ubuntu-latest
        aarch64-darwin:macos-15
      cache-pull-url: https://znix.zebradil.dev
      cache-public-key: znix.zebradil.dev:nvr0OQFRddbHGopQbyLbLXQnntFBDKp23tqQq+msppw=
      run-flake-update: ${{ github.event_name == 'workflow_dispatch' && inputs.run-flake-update }}
      auto-commit: ${{ github.event_name == 'workflow_dispatch' && inputs.run-flake-update }}
    secrets:
      cache-signing-key: ${{ secrets.CACHE_PRIVATE_KEY }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ci-push-ssh-key: ${{ secrets.CI_PUSH_DEPLOY_KEY }}
      cache-s3-url: ${{ secrets.CACHE_URL != '' && format('s3://{0}', secrets.CACHE_URL) || '' }}
